AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 200  # Default is 100

Metrics/MethodLength:
  Max: 20   # Default is 10

Metrics/AbcSize:
  Max: 25   # Default is 17

Metrics/CyclomaticComplexity:
  Max: 10   # Default is 7

Metrics/PerceivedComplexity:
  Max: 10   # Default is 8

Gemspec/DevelopmentDependencies:
  Enabled: false